ViewModels/ChooseLanguage.cs
namespace Lingva.ViewModels
{
    public class ChooseLanguage
    {
        public string Language { get; set; }
    }
}

Controllers/LessonCreateController.cs
using Lingva.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace Lingva.Controllers
{
    /// <summary>
    /// Класс управляет системой создания и добавления уроков в базу данных
    /// </summary>
    public class LessonCreateController : Controller
    {
        /* Методы, возвращающие IActionResult попарно разбиты. 
         * Методы с атрибутом HttpPost вызываются по нажатии на кнопку отправки формы
         * Методы без атрибута приравниваются к атрибуту HttpGet и вызываются при 
         * вызове самой страницы. 
         * Задача класса - пошагово создать урок, сохраняя промежуточный результат в базу данных */

        /// <summary>
        /// Первая стартовая страницы создания урока. На странице 3 радиокнопки с выбором языка
        /// </summary>
        public IActionResult ChooseLanguage() => View();
        
        /// <summary>
        /// Вызывается по нажатии на кнопку отправки формы в LessonCreate/ChooseLanguage.
        /// </summary>
        /// <param name="model">Объект модели с заполненным LanguageParent</param>
        [HttpPost("ChooseLanguage")]
        public IActionResult ChooseLanguage(Task model)
        {
            // Add to database then redirect
            return RedirectToAction("ChooseTheme", model);
        }

        /// <summary>
        /// Вторая страница создания урока. На странице выпадающее меню (внутри есть вариант "добавить") и 1 кнопка - "выбрать"
        /// </summary>
        /// <param name="model"></param>
        public IActionResult ChooseTheme(Task model)
        {
            List<int> numbers = new List<int>{ 1, 2, 3, 4, 5, 6 };
            ViewBag.IDs = numbers;
            return View(model);
        }

        /// <summary>
        /// Вызывается по нажатии на кнопку отправки формы в LessonCreate/ChooseTheme
        /// </summary>
        /// <param name="model">Объект модели с заполненным полем ThemeParentID</param>
        [HttpPost("ChooseTheme")]
        public IActionResult ChooseThemePost(Task model)
        {
            // Add to db and then redirect
            return RedirectToAction("ChooseLesson", model);
        }

        /// <summary>
        /// Третья страница создания урока. На ней выпадающее меню с функцией создания нового урока или выбором 
        /// существующего. И кнопка отправки формы.
        /// </summary>
        public IActionResult ChooseLesson(Task model)
        {
            List<int> numbers = new List<int> { 1, 2, 3, 4, 5, 6 };
            ViewBag.IDs = numbers;
            return View(model);
        }

        /// <summary>
        /// Вызывается при отправке формы третьего урока в LessonCreate/ChooseTask
        /// </summary>
        /// <param name="model">Заполненная модель с LessonParentID</param>
        [HttpPost("ChooseLesson")]
        public IActionResult ChooseLessonPost(Task model)
        {
            // Add to db
            return RedirectToAction("ChooseTaskType", model);
        }

        /// <summary>
        /// Четвёртая страница создания урока. На странице радиокнопки с типом задания, радиокнопки с типом наличия текста
        /// и кнопка "далее", отправляющая данные в форму
        /// </summary>
        public IActionResult ChooseTaskType(Task model) => View(model);

        /// <summary>
        /// Вызывается при отправке формы в LessonCreate/ChooseTaskType
        /// </summary>
        /// <param name="model">Модель с заполненным полем LessonType</param>
        [HttpPost("ChooseTaskType")]
        public IActionResult ChooseTaskTypePost(Task model)
        {
            // Add to db and then redirect
            return RedirectToAction("EditTask", model);
        }

        /// <summary>
        /// Пятая, конечная страница урока. Из неё можно попасть в редактирование полей и текста.
        /// </summary>
        public IActionResult EditTask(Task model)
        {
            return View(model);
        }
        
        /// <summary>
        /// Вызывается при отправке формы. Должна отредактировать сохраненное текстовое поле
        /// </summary>
        [HttpPost("EditTask")]
        public IActionResult EditTaskPost(Task model)
        {
            return View();
        }

        /// <summary>
        /// Шестая, необязательная страница создания урока. Открывает страницу редактирования полей
        /// </summary>
        public IActionResult EditTaskFields(Task model)
        {
            return View();
        }
        
        /// <summary>
        /// Вызывается по нажатии кнопки "сохранить" в поле для ответов к задаче у задания
        /// </summary>
        [HttpPost("EditTaskFields")]
        public IActionResult EditTaskFieldsPost(Task model)
        {
            return View();
        }

        /// <summary>
        /// Открывает страницу с полем ввода названия темы. 
        /// Вызывается по нажатии кнопки "Новая тема" в LessonCreate/ChooseTheme
        /// </summary>
        public IActionResult NewTheme()
        {
            return View();
        }

        /// <summary>
        /// Вызывается по нажатию кнопки "далее" после ввода названия урока
        /// </summary>
        [HttpPost("NewTheme")]
        public IActionResult NewThemePost(Task model)
        {
            return View();
        }

        /// <summary>
        /// Открывает страницу с полем ввода названия темы. 
        /// Вызывается по нажатии кнопки "Новый урок" в LessonCreate/ChooseLesson
        /// </summary>
        public IActionResult NewLesson()
        {
            return View();
        }

        /// <summary>
        /// Вызывается по нажатию кнопки "далее" после ввода названия урока
        /// </summary>
        [HttpPost("NewLesson")]
        public IActionResult NewLessonPost(Task model)
        {
            return View();
        }    
    }
}

Views/LessonCreate/ChooseLanguage.cshtml
@model Lingva.Models.Task
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @await Html.PartialAsync("_CssHeaderPartial")
    <link rel="stylesheet" href="../css/base.css" asp-append-version="true"/>
    <title>Choose Language</title>
</head>
<body>
    <h1 class="title">ВЫБЕРИТЕ ЯЗЫК:</h1>
    <div class="container">
        <div class="container__items">
            <form method="post" asp-controller="LessonCreate" asp-action="ChooseLanguage">
                English @Html.RadioButtonFor(m => m.LanguageParent, "English")
                Russian @Html.RadioButtonFor(m => m.LanguageParent, "Russian")
                Deutsch @Html.RadioButtonFor(m => m.LanguageParent, "Deutsch")
                <input type="submit" name="Далее" />
            </form>
        </div>

    </div>
</body>
</html>

Views/LessonCreate/ChooseLesson.cshtml
@model Lingva.Models.Task
@{
    Layout = null;
    List<int> IDs = ViewBag.IDs;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="../css/admin_css/choose-task.css" asp-append-version="true">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @await Html.PartialAsync("_CssHeaderPartial")
    <link rel="stylesheet" href="../css/base.css" asp-append-version="true">
    <title>Choose Task</title>
</head>
<body>
    @await Html.PartialAsync("_HeaderPartial")
    <div class="container">
        <div class="select_task_type">SELECT TASK TYPE:</div>
        <div class="main">
            <form method="post" asp-controller="LessonCreate" asp-action="ChooseLessonPost">
                @Html.HiddenFor(m => m.LanguageParent, Model.LanguageParent)
                @Html.HiddenFor(m => m.ThemeParentID, Model.ThemeParentID)
                @Html.DropDownListFor(m => m.LessonParentID, new SelectList(IDs), "Выберите урок:")
                <input type="submit" name="Далее" />
            </form>
        </div>
    </div>
</body>
</html>

Views/LessonCreate/ChooseTask.cshtml
@model Lingva.Models.Lesson
@{
    Layout = null;
}



<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="../css/admin_css/choose-task.css" asp-append-version="true">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @await Html.PartialAsync("_CssHeaderPartial")
    <link rel="stylesheet" href="../css/base.css" asp-append-version="true">
    <title>Choose Task</title>
</head>
<body>
    @await Html.PartialAsync("_HeaderPartial")
    <div class="container">
        <div class="select_task_type">SELECT TASK TYPE:</div>
        <div class="main">
            <form method="post" asp-controller="LessonCreate" asp-action="ChooseTaskPost">
                @Html.TextAreaFor(value => value.TextFieldContent, new { @class="textarea"})
                <p class="text">ADD TASK:</p>
                Number of tasks 0
                <input type="submit" name="submit" />
            </form>
        </div>
    </div>
</body>
</html>

Views/LessonCreate/ChooseTaskType.cshtml
@model Lingva.Models.Task
@{
    Layout = null;
}



<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="../css/admin_css/choose-tasktype.css" asp-append-version="true">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @await Html.PartialAsync("_CssHeaderPartial")
    <link rel="stylesheet" href="../css/base.css" asp-append-version="true">
    <title>Choose Task Type</title>
</head>
<body>
    @await Html.PartialAsync("_HeaderPartial")
    <h1 class="title">ВЫБЕРИТЕ ЯЗЫК:</h1>
    <div class="container">
        <form method="post" asp-controller="LessonCreate" asp-action="ChooseTaskTypePost">
            @Html.HiddenFor(m => m.LanguageParent, Model.LanguageParent)
            @Html.HiddenFor(m => m.LessonParentID, Model.LessonParentID)
            @Html.HiddenFor(m => m.ThemeParentID, Model.ThemeParentID)
            <div class="container__items">
                Fill @Html.RadioButtonFor(type => type.LessonType, "fill")
                Trans @Html.RadioButtonFor(type => type.LessonType, "trans")
                Match @Html.RadioButtonFor(type => type.LessonType, "match")
            </div>
            <input type="submit" name="submit" />
        </form>
    </div>
</body>
</html>

Views/LessonCreate/ChooseTheme.cshtml
@model Lingva.Models.Lesson
@{ 
    Layout = null;
    List<int> IDs = ViewBag.IDs;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @await Html.PartialAsync("_CssHeaderPartial")
    <link rel="stylesheet" href="../css/base.css" asp-append-version="true">
    <link rel="stylesheet" href="../css/admin_css/choose-theme.css" asp-append-version="true">
    <title>Choose Theme</title>
</head>
<body>
    @await Html.PartialAsync("_HeaderPartial")
    <div class="container">
        <p class="nomer-temi">ВЫБЕРИТЕ НОМЕР ТЕМЫ:</p>

        <form method="post" asp-controller="LessonCreate" asp-action="ChooseThemePost">
            @Html.HiddenFor(m => m.LanguageParent, Model.LanguageParent)
            @Html.DropDownListFor(m => m.ThemeParentID, new SelectList(IDs), "Выберите тему:")
            <input type="submit" name="Далее" />
        </form>

        <button class="new-lesson">НОВЫЙ УРОК</button>
    </div>
</body>
</html>

Views/LessonCreate/EditTask.cshtml
@model Lingva.Models.Task
@{Layout = null;}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @await Html.PartialAsync("_CssHeaderPartial")
    <link rel="stylesheet" href="../css/base.css" asp-append-version="true" />
    <link rel="stylesheet" href="../css/admin_css/edit_task.css">
    <title>Document</title>
</head>
<body>
    @await Html.PartialAsync("_HeaderPartial")
    <div class="container">
        <h1 class="title">РЕДАКТИРОВАНИЕ ЗАДАНИЯ</h1>
        <form method="post" class="form" asp-controller="LessonCreate" asp-action="EditTaskPost">
            <div class="textarea_container">
                @Html.TextAreaFor(m => m.TextFieldContent, new { @class = "textarea" })
            </div>
            <input class="save_text_btn" type="submit" name="СОХРАНИТЬ ТЕКСТ"/>
        </form>
        <div class="bottom_block">
            <h2 class="subtitle">Количество заданий в уроке: $</h2>
            <button class="edit_fields_btn">Редактировать</button>
        </div>
    </div>

</body>
</html>

Views/LessonCreate/EditTaskFields.cshtml
@{ Layout = null; }

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @await Html.PartialAsync("_CssHeaderPartial") 
    <link rel="stylesheet" href="../css/base.css">
    <link rel="stylesheet" href="../css/admin_css/edit_task_fields.css">
    <title>Document</title>
</head>
<body>
    @await Html.PartialAsync("_HeaderPartial")
    <div class="container">
        <h1 class="title">РЕДАКТИРОВАНИЕ ЗАДАНИЯ</h1>
        <form action="" class="form">
            <div class="field_container">
                <label class="field_item primary" for="">Текст</label>
                <textarea class="input_field" type="text" name="" id=""></textarea>
                <label class="field_item secondary" for="">Правильный ответ</label>
                <input class="input_field" type="text" name="" id="">
                <div class="button_container field_item">
                    <button class="save_field_btn">Сохранить</button>
                </div>
            </div>
        </form>
        <div class="navigation_buttons">
            <button class="navigation_button">ДОБАВИТЬ</button>
            <button class="navigation_button">НАЗАД</button>
        </div>
    </div>
</body>
</html>

Views/LessonCreate/NewLesson.cshtml
@model Lingva.Models.Lesson1
@{ Layout = null; }

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @await Html.PartialAsync("_CssHeaderPartial")
    <link rel="stylesheet" href="../css/base.css">
    <link rel="stylesheet" href="../css/admin_css/new_theme.css">
    <title>Document</title>
</head>
<body>
    @await Html.PartialAsync("_HeaderPartial")
    <div class="container">
        <h1>ВВЕДИТЕ НАЗВАНИЕ НОВОГО УРОКА ДЛЯ {theme}</h1>
        <form class="form" method="post" asp-controller="LessonCreate" asp-action="ChooseTaskTypePost">
            @Html.TextBoxFor(m => m.LessonTitle)
            <input type="submit" name="ДАЛЕЕ" />
        </form>
    </div>
</body>
</html>

Views/LessonCreate/NewTheme.cshtml
@model Lingva.Models.Theme
@{ Layout = null; }

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @await Html.PartialAsync("_CssHeaderPartial")
    <link rel="stylesheet" href="../css/base.css">
    <link rel="stylesheet" href="../css/admin_css/new_theme.css">
    <title>Document</title>
</head>
<body>
    @await Html.PartialAsync("_HeaderPartial")
    <div class="container">
        <h1>ВВЕДИТЕ НАЗВАНИЕ НОВОЙ ТЕМЫ ДЛЯ {language}</h1>
        <form class="form" method="post" asp-controller="LessonCreate" asp-action="ChooseTaskTypePost">
            @Html.TextBoxFor(m => m.ThemeTopic)
            <input type="submit" name="ДАЛЕЕ" />
        </form>
    </div>
</body>
</html>